apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
spec:
  template:
    spec:
      containers:
      - command:
        - /bin/rollouts-controller
        image: argoproj/argo-rollouts:v0.1.0
        imagePullPolicy: Always
        name: argo-rollouts