apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rollouts.argoproj.io
spec:
  group: argoproj.io
  version: v1alpha1
  names:
    kind: Rollout
    plural: rollouts
  scope: Namespaced
